In [2]:
from audIBle.data.datasets import ESC_50

In [3]:
root = "/lium/corpus/vrac/tmario/"
dataset = ESC_50(root=root, train=True)

Files already downloaded and verified


0it [00:00, ?it/s]

1600it [00:05, 292.17it/s]


In [ ]:
import torch
data_loader = torch.utils.data.DataLoader(dataset, batch_size=1, shuffle=True)
for i, (audio, target) in enumerate(data_loader):
    pass

0
torch.Size([1, 1, 220500])
torch.Size([1])
tensor([38])
1
torch.Size([1, 1, 220500])
torch.Size([1])
tensor([19])
2
torch.Size([1, 1, 220500])
torch.Size([1])
tensor([39])
3
torch.Size([1, 1, 220500])
torch.Size([1])
tensor([10])
4
torch.Size([1, 1, 220500])
torch.Size([1])
tensor([28])
5
torch.Size([1, 1, 220500])
torch.Size([1])
tensor([30])
6
torch.Size([1, 1, 220500])
torch.Size([1])
tensor([3])
7
torch.Size([1, 1, 220500])
torch.Size([1])
tensor([41])
8
torch.Size([1, 1, 220500])
torch.Size([1])
tensor([24])
9
torch.Size([1, 1, 220500])
torch.Size([1])
tensor([13])
10
torch.Size([1, 1, 220500])
torch.Size([1])
